"""add_notifications_and_audit_logs

Revision ID: be8c7a7fb57e
Revises: c85aab690795
Create Date: 2026-02-26 04:13:00.290914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8c7a7fb57e'
down_revision: Union[str, Sequence[str], None] = 'c85aab690795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_org_entity', ['org_id', 'entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_org', ['user_id', 'org_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'read'], unique=False)

    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.create_index('ix_ai_systems_org_risk', ['org_id', 'risk_classification'], unique=False)

    with op.batch_alter_table('bias_audits', schema=None) as batch_op:
        batch_op.create_index('ix_bias_audits_system_org', ['ai_system_id', 'org_id'], unique=False)

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.create_index('ix_compliance_checks_system_org_status', ['ai_system_id', 'org_id', 'status'], unique=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_org_severity_status', ['org_id', 'severity', 'status'], unique=False)

    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.create_index('ix_model_cards_system_org', ['ai_system_id', 'org_id'], unique=False)

    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.create_index('ix_regulations_jurisdiction_category', ['jurisdiction', 'category'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_org_id', ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_org_id')

    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index('ix_regulations_jurisdiction_category')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_model_cards_system_org')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_org_severity_status')

    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_compliance_checks_system_org_status')

    with op.batch_alter_table('bias_audits', schema=None) as batch_op:
        batch_op.drop_index('ix_bias_audits_system_org')

    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_systems_org_risk')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index('ix_notifications_user_org')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_org_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user')
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index('ix_audit_logs_org_entity')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
