"""initial_schema

Revision ID: c85aab690795
Revises: 
Create Date: 2026-02-26 03:50:59.225462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85aab690795'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('enforcement_date', sa.DateTime(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_jurisdiction'), ['jurisdiction'], unique=False)

    op.create_table('service_providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('task_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_records_org_id'), ['org_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_provider_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_provider_id'], ['service_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ai_systems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('data_types', sa.JSON(), nullable=True),
    sa.Column('deployment_regions', sa.JSON(), nullable=True),
    sa.Column('risk_classification', sa.Enum('unacceptable', 'high', 'limited', 'minimal', 'unclassified', name='risk_classification_enum'), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_systems_org_id'), ['org_id'], unique=False)

    op.create_table('company_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('jurisdictions', sa.JSON(), nullable=True),
    sa.Column('risk_appetite', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_profiles_org_id'), ['org_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('doc_type', sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'TEXT', 'PDF', name='ingesttype'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('intelligence_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_source_file_name'), ['source_file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='user_role_enum'), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bias_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ai_system_id', sa.String(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('dataset_description', sa.Text(), nullable=True),
    sa.Column('demographic_parity_score', sa.Float(), nullable=True),
    sa.Column('disparate_impact_ratio', sa.Float(), nullable=True),
    sa.Column('overall_status', sa.Enum('pass', 'fail', 'conditional', name='audit_status_enum'), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bias_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bias_audits_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bias_audits_org_id'), ['org_id'], unique=False)

    op.create_table('compliance_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ai_system_id', sa.String(), nullable=False),
    sa.Column('regulation_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('compliant', 'non_compliant', 'partial', 'pending', name='compliance_status_enum'), nullable=True),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='check_priority_enum'), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_checks_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_regulation_id'), ['regulation_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ai_system_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='incident_severity_enum'), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('investigating', 'mitigating', 'resolved', 'closed', name='incident_status_enum'), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('filing_status', sa.String(), nullable=True),
    sa.Column('filing_deadline', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_org_id'), ['org_id'], unique=False)

    op.create_table('model_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ai_system_id', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_cards_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_cards_org_id'), ['org_id'], unique=False)

    op.create_table('text_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('figure_ids', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_chunks_vector_id'), ['vector_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_chunks_vector_id'))

    op.drop_table('text_chunks')
    with op.batch_alter_table('model_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_cards_org_id'))
        batch_op.drop_index(batch_op.f('ix_model_cards_ai_system_id'))

    op.drop_table('model_cards')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_org_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_ai_system_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_checks_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_checks_org_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_checks_ai_system_id'))

    op.drop_table('compliance_checks')
    with op.batch_alter_table('bias_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bias_audits_org_id'))
        batch_op.drop_index(batch_op.f('ix_bias_audits_ai_system_id'))

    op.drop_table('bias_audits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_source_file_name'))

    op.drop_table('documents')
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_profiles_org_id'))

    op.drop_table('company_profiles')
    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_systems_org_id'))

    op.drop_table('ai_systems')
    op.drop_table('organizations')
    with op.batch_alter_table('task_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_records_org_id'))

    op.drop_table('task_records')
    op.drop_table('service_providers')
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_jurisdiction'))

    op.drop_table('regulations')
    # ### end Alembic commands ###
